id: 0
team_id: 12

# kick
kick_key_is_y: true
dribble_to_kick: 
  kid: [-2.3, 2.3]
  adult: [-3.3, 3.3]
kick_to_dribble: 
  kid: [-1.7, 1.7]
  adult: [-2.7, 2.7]

# field
field_size:
  kid: [9, 6] 
  adult: [14, 9]

league: "adult" # "kid"

# ball
close_to_ball_threshold: 0.5

# velocities
walk_vel_x: 0.5
walk_vel_y: 0.5
walk_vel_theta: 1
max_walk_vel_x: 0.5
max_walk_vel_y: 0.5
max_walk_vel_theta: 1

# networking
server_ip: "192.168.9.105"
server_port: 8002
auto_find_server_ip: true
auto_find_server_ip_listen_port: 8003
auto_find_server_ip_token: "NjM5NWVkMSAgLQo"
max_buffer_size: 1024
offline_time: 5  # seconds
start_walk_into_field_time: 20  # seconds

# vision
vision_size: [1280, 736]  # the size of photos used by vision
pos_accuracy_add:
  # the score 'add' to the self_pos_accuracy
  # when these items appears in vision
  "0": 0  # ballsel
  "1": 10  # goalpost
  "2": 0  # robot
  "3": 5  # L-Intersection
  "4": 5  # T-Intersection
  "5": 5  # X-Intersection
predict_ball_pos: true
predict_ball_pos_in_map: true
move_head_time_gap: 0.1  # second
move_head_phase_time_gap: 0.8  # second
ball_accuracy_integrated_factor: 0.1
looking_at_ball_integrated: [0.1, 0.1]  # integrated arguments
looking_at_ball_arguments:
  - [0.4, 0.0, 0.2]  # P, I, D of head
  - [0.4, 0.0, 0.2]  # P, I, D of neck
self_pos_accuracy_critical: 0.0  # when accuracy is lower than this,
# self_pos is considered lost
ball_pos_accuracy_critical: 0.1  # when accuracy is lower than this,
# ball is considered lost
_ball_pos_accuracy_look_around: 0.5  # when accuracy is lower than this,
# camera is looking around
search_ball_head_angle:
  - [0.0, -0.9]
  - [0.9, 0.0]
  - [0.0, 0.0]
  - [0.9, 0.0]
  - [0.0, 0.9]
  - [0.9, 0.0]
# camera is looking around

# sundry
if_can_kick: false

# statemachines params
dribble:
  angle_to_ball_adjust_threshold_rad: 11.46
  good_angle_to_goal_threshold_degree: 10
  goal_center_bias_m: 0.5
  walk_vel_x: 1
  back_vel: 0.05
  horizontal_adjust_vel_y: 0.6
  horizontal_adjust_vel_theta: 0.5
  walk_vel_theta: 1
  adjust_angle_to_goal_vel_y: 0.5
  adjust_angle_to_goal_vel_theta: 0.5
  min_ball_distance_m: 0.0
  max_ball_distance_m: 0.40
  good_horizontal_position_to_ball_upper_threshold_m: 0.15
  good_horizontal_position_to_ball_lower_threshold_m: 0.05
  lost_angle_to_target_threshold_degree: 20
  lost_ball_x_threshold_m: 0.08
  lost_ball_distance_threshold_m: 0.8
  dribble_0_y: 7
  dribble_forward_vel_y: 0.5
  camera_bias: 0.06  # camera bias in x direction
find_ball:
  angle_threshold_degrees: 10
  rotation_vel_theta: 1
  rotation_timeout_seconds: 10
  protection_pose_duration: 0.5
go_back_to_field:
  aim_x: 1.5
  aim_y: 2.0
  aim_yaw: 0
  min_dist: 0.5
  coarse_yaw_threshold_degree: 30
  fine_yaw_start_threshold_degree: 20
  fine_yaw_end_threshold_degree: 5
  good_yaw_threshold_degree: 10
  walk_vel_x: 0.5
  walk_vel_theta: 1
  arrive_trust_time: 20
chase:
  close_angle_threshold_rad: 0.8
  walk_vel_x: 1
  walk_vel_theta: 1
  default_chase_distance: 0.4
kick:
  good_angle_threshold_degree: 10
  really_bad_angle_threshold_degree: 30
  horizontal_position_threshold_mm: 30
  horizontal_adjust_threshold_degree: 5
  min_kick_distance_m: 0
  max_kick_distance_m: 0.38
  lost_ball_distance_threshold_m: 0.8
  forward_vel: 0.1
  lateral_vel: 0.04
  rotate_vel_theta: 0.5
  horizontal_adjust_forward_vel: 0.05
  rotate_vel_y: 0.05
goalkeeper:
  safe_area_threshold: -1