control_interval_s: 0.2
broadcast_address: "192.168.30.255"

shooting:
  ball_in_control_threshold_m: 0.5
  ball_out_of_control_threshold_m: 1.2
  close_to_ball_threshold_m: 0.8

defending:
  ball_in_control_threshold_m: 0.5
  ball_out_of_control_threshold: 1.2
  close_to_ball_threshold: 0.8
  no_control_chase_distance: 1.2

attacking:
  ball_in_control_threshold_m: 0.5
  ball_out_of_control_threshold_m: 1.2
  close_to_ball_threshold_m: 1.0
  no_control_chase_distance: 1.2

roles_to_id:
  forward_1: 2
  forward_2: 3
  defender_1: 4
  defender_2: 3
  goalkeeper: 6

backfield_machine: "run_attack"
midfield_machine: "run_attack"
frontfield_machine: "run_attack"

robot_server:
  send_robot_data:
    port: 8001
    frequency: 10
    secret: "YXdpb3BqeHo7bHas"
  receive_from_server:
    port: 8002
    timeout: 10
    secret: "PIDcvpasdvfpIFES"
  find_server_ip:
    constant_server_ip: "auto-find"
    port: 8003
    secret: "a2xzYXZoO29hd2pp"